/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Desafio01;
import javax.swing.DefaultListModel;

/**
 *
 * @author bruno
 */
public class Desafio01 extends javax.swing.JFrame {

    /**
     * Creates new form Desafio01
     */
    public Desafio01() {
        initComponents();
        /*lstMil.setVisible(false);
        lstMilhao.setVisible(false);
        scrMil.setVisible(false);
        scrMilhao.setVisible(false);*/
        txtDescricao.setText("Pressionando o botão abaixo, você verá uma lista de números que quando multiplicados pelo seu valor reverso resultará em um número ímpar menor que um milhão.");
        txtDescricao.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnMilhao = new javax.swing.JButton();
        scrMilhao = new javax.swing.JScrollPane();
        lstMilhao = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Desafio 01");
        jLabel1.setToolTipText("");

        btnMilhao.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnMilhao.setText("Mostrar");
        btnMilhao.setToolTipText("");
        btnMilhao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMilhaoActionPerformed(evt);
            }
        });

        scrMilhao.setViewportView(lstMilhao);

        txtDescricao.setColumns(20);
        txtDescricao.setLineWrap(true);
        txtDescricao.setRows(4);
        txtDescricao.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescricao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(btnMilhao))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrMilhao, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnMilhao)
                .addGap(18, 18, 18)
                .addComponent(scrMilhao, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMilhaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMilhaoActionPerformed
        // TODO add your handling code here:
        DefaultListModel lista = new DefaultListModel();       
        int soma = 0;
        for(int n = 0; soma <1000000; n++){
            if (validaNumeros(n) == true){
                int nReverso = inverteNumero(n);
                soma = n + nReverso;
                if(soma % 2 != 0){
                    lista.addElement(n + " + " + nReverso + " = " + soma);
                }
            }
        }
        lstMilhao.setModel(lista);
        //lstMil.setVisible(true);
        //scrMil.setVisible(true);
    }//GEN-LAST:event_btnMilhaoActionPerformed

    public static boolean validaNumeros(int numero) {
        String a = Integer.toString(numero);
        int b = a.length();
        String c = a.substring(b - 1, b);
        if(c.equals("0")){
            return false;
        }else{
            return true;
        }
			
    }
    public static int inverteNumero(int numero) {
        int numeroInvertido = 0;

        while (numero > 0) {
            numeroInvertido *= 10;
            numeroInvertido += (numero % 10);
            numero /= 10;
        }
        return numeroInvertido;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desafio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desafio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desafio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desafio01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desafio01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMilhao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstMilhao;
    private javax.swing.JScrollPane scrMilhao;
    private javax.swing.JTextArea txtDescricao;
    // End of variables declaration//GEN-END:variables
}
